# Generated by Django 4.1.7 on 2023-04-07 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField()),
                ('count_trades', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('simbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.simbol')),
            ],
        ),
    ]
