# Generated by Django 4.1.7 on 2023-04-18 16:45

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_cryptotransaction_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Big_Limits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('is_purchase', models.BooleanField(default=True)),
                ('volume', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None)),
                ('timestamp', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), default=list, size=None)),
                ('changes', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None)),
                ('simbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.simbol')),
            ],
        ),
    ]
