# Generated by Django 4.1.7 on 2023-04-18 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_big_limits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Big_Limits',
            new_name='BigLimits',
        ),
    ]
