# Generated by Django 4.1.7 on 2023-04-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_big_limits_biglimits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biglimits',
            name='price',
            field=models.CharField(max_length=12),
        ),
    ]
