# Generated by Django 4.1.7 on 2023-05-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_chatsubid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsubid',
            name='chatId',
            field=models.IntegerField(unique=True),
        ),
    ]
