# Generated by Django 4.1.7 on 2023-05-23 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_chatsubid_chatid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigLimitsEz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField()),
                ('is_purchase', models.BooleanField(default=True)),
                ('simbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.simbol')),
            ],
        ),
    ]
