# Generated by Django 4.1.7 on 2023-05-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_biglimitsez_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='biglimitsez',
            name='round',
            field=models.FloatField(default=0.0),
        ),
    ]
