# Generated by Django 4.1.7 on 2023-05-23 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_biglimitsez_round'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biglimitsez',
            old_name='round',
            new_name='range',
        ),
    ]
