# Generated by Django 4.1.7 on 2023-05-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_rename_round_biglimitsez_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('table', models.JSONField()),
            ],
        ),
    ]
